### ISSUE TITLE
Use docker multi-platform cross-compiler for AMD64 and ARM64 deployment 

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-fhwa-OPS/V2X-Hub#331]
### Types of Issue

- [ ] Anomaly report (something appears to not work correctly)
- [ x ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

Hello,

Please refer to such URL: https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/

I guess it would be better to maintain the releases with same Image name for different platforms, thru this 'multi-platform, cross-compiler' method.

That is, the image name could be unified to be same name, e.g. 'v2xhub' (no 'v2xhubamd', no 'v2xhubarm') and docker pull correct image type via 'platform' (or host's architecture); similar for 'php' and 'port-drayage-webservice' images.

FYR, thank you.
### Expected behavior
NA
### Actual behavior

NA
### Steps to reproduce the actual behavior

NA
### Related work

NA

**Comment by rob-baily** [comment]
I tried a brief test using the branch https://github.com/usdot-fhwa-OPS/V2X-Hub/tree/multi_arch_build which is using an emulator to build the arm image.  This timed out so this solution looks unworkable. 

It looks this would need to be handled by a longer term approach of:

- Compiling the items needed and create artifacts in CI (maybe Debian packages) for them rather than compiling in place and including everything in the deployed image.
- Creating docker images using the CI created artifacts and whatever run-time libraries need to be installed.
- Splitting up the Dockerfile as mentioned in the link above and enabling cross compiling on the C and C++ classes.

**Comment by jwillmartin** [comment]
Addressed with:
VH-1295
VH-1319
