### ISSUE TITLE
Support CI builds for forked pull requests

### ISSUE THREAD

**Issue by codygarver** [usdot-fhwa-OPS/V2X-Hub#450]
### Types of Issue

- [ - ] Anomaly report (something appears to not work correctly)
- [ ] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### V2XHUB version where this issue was discovered
develop

### Actual behavior

Opening a PR from a forked repo doesn't pass CI because CI tries to do a docker push with the base repo's secret

We need to...
* centralize the dependency installation to a script where possible
* use dependency install script in relevant Dockerfile and CircleCI where needed
* install Sonar only in CI
* get rid of any Dockerfile(s) only used for CI purposes
* only push desirable CI builds to dockerhub

**Comment by rob-baily** [comment]
@codygarver I have pushed some changes in the branch https://github.com/usdot-fhwa-OPS/V2X-Hub/tree/ci_refactor_for_forks which I think covers the points above. One question though is that I see that we use the env SONAR_SCANNER_TOKEN during the Sonar scan.   Is that not a protected variable that would be hidden from forks?

To the points above:

- There is scripts/install_dependencies.sh which is used in the Dockerfile and CI build for the core OS dependencies.
- Sonar now no longer uses a built Docker image to run things.  I copied a number of lines from Carma Streets.  Seems like there might be some opportunity to reuse stuff, maybe in the future.
- I removed Dockerfile-depl and left just Dockerfile.
- I did not change anything for what gets pushed so maybe that needs to be updated.

One other thing is that I was not sure how to configure the Sonar job so I have it as branches but ignoring the "develop" branch.  This is probably not correct.

I did confirm that the amd image works as expected in a deployment.

Feel free to checkout the branch yourself and make any changes as necessary and I am happy to discuss anything in it.  I did not try it on a forked PR to see either so that will need to be done.

**Comment by rob-baily** [comment]
I looked online and based on this thread https://community.sonarsource.com/t/code-analysis-on-pull-request-from-forked-repository-with-github-actions/43986 Sonar does not support scans on forked PRs.  It is on their roadmap.

**Comment by rob-baily** [comment]
Some notes on this:

- You can see a successful build of a forked PR at https://app.circleci.com/pipelines/github/usdot-fhwa-OPS/V2X-Hub/2060/workflows/cfc387e5-e776-493a-ae66-539fb8fed876.  You will see that it only runs the docker builds because we cannot run the Sonar Scanner on a forked PR.
- In builds for the develop branch starting with https://app.circleci.com/pipelines/github/usdot-fhwa-OPS/V2X-Hub/2073/workflows/3772f1ef-c4a4-429c-b2f9-0291f152f2f7 you will see that the Sonar step is run in parallel with the docker builds as it now does its own docker build using some of the scripts that are available instead of using a separate Dockerfile.
- Cleaned up some references in Markdown files that gave manual instructions that were duplicated or out of date.  These now reference script files that do the work that was listed as manual.  These scripts are included in the docker build so anytime they are modified there is now no need to update documentation.  Only if a new script is added do docs need to be added.
